version: '3'
services: 
  web:
    restart: always
    build: ./blog
    volumes: 
      - ./blog/:/var/www/
    depends_on: 
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes: 
      - "./.docker/dbdata:/var/lib/postgresql/data"

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8080:80"
    volumes: 
      - ./blog/:/var/www
    depends_on:
        - web